version: '3'

services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tsv_to_csv
    volumes:
      - ./code:/code
      - ${DATA_DIR}:/data
      - ${OUTPUT_DIR}:/output
  report:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: report_csv_to_osprey
    volumes:
      - ./code/osprey:/code
      - ${DATA_DIR}:/data
      - ${OUTPUT_DIR}:/output